name: Docker Image CI

on:
  push:
    branches:
      - 'main'
      - 'feature/**'
  pull_request:
    branches:
      - 'main'

jobs:
  build:
    runs-on: alpine:3.14
    steps:
    - uses: actions/checkout@v3
    - name: Build the Docker image
      run: cd modbus_mqtt_bridge && docker build . --file Dockerfile --tag ModbusMQTTBridge:$(date +%s)
